<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>DeployAgent</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DeployAgent.Core\DeployAgent.Core.csproj" />
    <ProjectReference Include="..\DeployAgent.V1\DeployAgent.V1.csproj" />
    <ProjectReference Include="..\DeployAgent.V2\DeployAgent.V2.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
