<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.AI.Agents.Persistent" Version="1.1.0" />
    <PackageReference Include="Azure.Identity" Version="1.17.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DeployAgent.Core\DeployAgent.Core.csproj" />
  </ItemGroup>

</Project>
